# Generated by Django 4.0 on 2021-12-14 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genere',
            options={'verbose_name': 'Genere', 'verbose_name_plural': 'Generes'},
        ),
        migrations.AddField(
            model_name='movieshot',
            name='movie',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='movieshot',
            name='image',
            field=models.ImageField(upload_to='movie_shot/'),
        ),
    ]
